"""Concern-to-document routes for workflow routing."""

from __future__ import annotations

from typing import Dict, Tuple


PUBLIC_DISCOVERY_DOCS = ("common/public-discovery.md",)


CONCERNS: Dict[str, Tuple[str, ...]] = {
    "security": ("common/secure-development-baseline.md", "common/security-privacy-review.md"),
    "runtime-url": ("common/runtime-url-configuration.md",),
    "url": ("common/runtime-url-configuration.md",),
    "config": ("common/runtime-url-configuration.md",),
    "intake": ("common/task-intake-effort-routing.md", "workflows/request-triage.md"),
    "effort": ("common/task-intake-effort-routing.md",),
    "testing": ("common/testing.md", "common/scenario-driven-testing.md", "common/verification-policy.md"),
    "test": ("common/testing.md", "common/scenario-driven-testing.md", "common/verification-policy.md"),
    "verification": (
        "common/verification-policy.md",
        "common/testing.md",
        "common/scenario-driven-testing.md",
        "common/definition-of-done.md",
    ),
    "done": ("common/definition-of-done.md", "common/verification-policy.md"),
    "definition-of-done": ("common/definition-of-done.md", "common/verification-policy.md"),
    "api": ("common/api-contract-compatibility.md",),
    "architecture": ("common/architecture-selection.md", "common/architecture-design.md", "common/app-architecture.md"),
    "swift": (
        "platforms/swift/swift-architecture.md",
        "platforms/swift/swift-code-structure.md",
        "platforms/swift/swift-design-system.md",
        "platforms/swift/swift-review.md",
    ),
    "asset": ("common/asset-lifecycle.md",),
    "assets": ("common/asset-lifecycle.md",),
    "structure": ("common/code-structure-ownership.md",),
    "module": ("common/code-structure-ownership.md",),
    "reusability": ("common/reusable-code-design.md", "common/component-api-design.md"),
    "component": ("common/component-api-design.md",),
    "component-api": ("common/component-api-design.md",),
    "state": ("common/state-modeling.md",),
    "error": ("common/error-modeling.md",),
    "errors": ("common/error-modeling.md",),
    "ui": ("common/design-system.md", "common/component-api-design.md", "common/ui-visual-verification.md"),
    "design": ("common/design-system.md", "common/component-api-design.md", "common/ui-visual-verification.md"),
    "design-system": ("common/design-system.md", "common/component-api-design.md", "common/ui-visual-verification.md"),
    "tokens": ("common/design-system.md", "common/ui-visual-verification.md"),
    "accessibility": ("common/accessibility-i18n.md",),
    "i18n": ("common/accessibility-i18n.md",),
    "localization": ("common/accessibility-i18n.md",),
    "number-format": ("common/accessibility-i18n.md",),
    "number": ("common/accessibility-i18n.md",),
    "numbers": ("common/accessibility-i18n.md",),
    "numeric": ("common/accessibility-i18n.md",),
    "unit": ("common/accessibility-i18n.md",),
    "units": ("common/accessibility-i18n.md",),
    "measurement": ("common/accessibility-i18n.md",),
    "measurements": ("common/accessibility-i18n.md",),
    "currency": ("common/accessibility-i18n.md",),
    "display-value": ("common/accessibility-i18n.md",),
    "display-values": ("common/accessibility-i18n.md",),
    "writing": ("common/human-authored-writing.md", "common/writing-workspace.md"),
    "prose": ("common/human-authored-writing.md", "common/writing-workspace.md"),
    "voice": ("common/human-authored-writing.md",),
    "copy": ("common/human-authored-writing.md", "common/accessibility-i18n.md"),
    "skill": ("common/agent-skill-card-anatomy.md", "workflows/documentation-update.md"),
    "skills": ("common/agent-skill-card-anatomy.md", "workflows/documentation-update.md"),
    "skill-card": ("common/agent-skill-card-anatomy.md", "workflows/documentation-update.md"),
    "card-anatomy": ("common/agent-skill-card-anatomy.md", "workflows/documentation-update.md"),
    "source-driven": ("common/source-driven-development.md",),
    "source": ("common/source-driven-development.md",),
    "official-docs": ("common/source-driven-development.md",),
    "doubt": ("common/doubt-driven-development.md", "workflows/multi-perspective-review.md"),
    "doubt-driven": ("common/doubt-driven-development.md", "workflows/multi-perspective-review.md"),
    "incremental": ("common/incremental-implementation.md",),
    "slice": ("common/incremental-implementation.md",),
    "slicing": ("common/incremental-implementation.md",),
    "deprecation": ("common/deprecation-migration.md", "common/release-deployment.md"),
    "migration": ("common/deprecation-migration.md", "common/data-persistence-sync.md"),
    "ci": ("common/ci-cd-automation.md",),
    "cd": ("common/ci-cd-automation.md",),
    "automation": ("common/ci-cd-automation.md",),
    "shipping": ("common/ci-cd-automation.md", "workflows/release-readiness.md", "common/web-deployment-versioning.md"),
    "commit": ("common/commit-workflow.md", "common/worktree-hygiene.md", "workflows/review-and-commit.md"),
    "branch": ("common/commit-workflow.md", "common/worktree-hygiene.md", "workflows/review-and-commit.md"),
    "branching": ("common/commit-workflow.md", "common/worktree-hygiene.md", "workflows/review-and-commit.md"),
    "push": ("common/commit-workflow.md", "common/worktree-hygiene.md", "common/secure-development-baseline.md"),
    "pr": ("common/commit-workflow.md", "common/worktree-hygiene.md", "workflows/review-and-commit.md"),
    "pull-request": ("common/commit-workflow.md", "common/worktree-hygiene.md", "workflows/review-and-commit.md"),
    "tag": (
        "common/commit-workflow.md",
        "common/worktree-hygiene.md",
        "workflows/release-readiness.md",
        "common/release-deployment.md",
        "common/release-versioning.md",
    ),
    "webperf": (
        "common/performance-verification.md",
        "common/web-performance-verification.md",
        "common/browser-runtime-testing.md",
    ),
    "performance": ("common/performance-verification.md",),
    "browser-testing": ("common/browser-runtime-testing.md", "common/ui-visual-verification.md"),
    "devtools": ("common/browser-runtime-testing.md",),
    "persistence": ("common/data-persistence-sync.md",),
    "cache": ("common/server-side-caching.md",),
    "release": (
        "workflows/release-readiness.md",
        "common/release-deployment.md",
        "common/release-versioning.md",
        "common/web-deployment-versioning.md",
    ),
    "dependency": ("common/dependency-policy.md",),
    "generated": ("common/generated-files-policy.md",),
    "worktree": ("common/worktree-hygiene.md",),
    "stack": ("common/stack-discovery.md",),
    "failure": ("common/tool-failure-recovery.md",),
    "interaction": ("common/agent-interaction.md",),
    "local-tools": ("common/local-tools.md", "docs/agent-runtime-integration.md"),
    "metering": ("common/local-tools.md",),
    "telemetry": ("common/local-tools.md",),
    "usage": ("common/local-tools.md",),
    "defensive": ("common/defensive-boundaries.md",),
    "observability": ("common/observability-error-handling.md", "common/error-modeling.md"),
    "discovery": PUBLIC_DISCOVERY_DOCS,
    "seo": PUBLIC_DISCOVERY_DOCS,
    "ai-mode": PUBLIC_DISCOVERY_DOCS,
    "ai-overviews": PUBLIC_DISCOVERY_DOCS,
    "ai-search": PUBLIC_DISCOVERY_DOCS,
    "ai-search-optimization": PUBLIC_DISCOVERY_DOCS,
    "aeo": PUBLIC_DISCOVERY_DOCS,
    "answer-engine": PUBLIC_DISCOVERY_DOCS,
    "answer-engine-optimization": PUBLIC_DISCOVERY_DOCS,
    "canonical": PUBLIC_DISCOVERY_DOCS,
    "generative-ai": PUBLIC_DISCOVERY_DOCS,
    "generative-ai-search": PUBLIC_DISCOVERY_DOCS,
    "geo": PUBLIC_DISCOVERY_DOCS,
    "llms": PUBLIC_DISCOVERY_DOCS,
    "llms-txt": PUBLIC_DISCOVERY_DOCS,
    "open-graph": PUBLIC_DISCOVERY_DOCS,
    "robots": PUBLIC_DISCOVERY_DOCS,
    "sitemap": PUBLIC_DISCOVERY_DOCS,
    "structured-data": PUBLIC_DISCOVERY_DOCS,
    "wiki": ("workflows/documentation-update.md", "common/llm-wiki-documentation.md"),
    "auth": ("product-patterns/auth-rbac-permissions.md", "product-patterns/auth-rbac-implementation.md"),
    "invite": ("product-patterns/invitation-workflows.md", "product-patterns/invitation-implementation.md"),
    "billing": (
        "product-patterns/billing-entitlements.md",
        "product-patterns/billing-entitlements-implementation.md",
    ),
    "credential-broker": ("product-patterns/agent-credential-broker-ideation.md",),
    "agent-credentials": ("product-patterns/agent-credential-broker-ideation.md",),
    "brokered-credentials": ("product-patterns/agent-credential-broker-ideation.md",),
    "capability-token": ("product-patterns/agent-credential-broker-ideation.md",),
    "egress-control": ("product-patterns/agent-credential-broker-ideation.md",),
}


BASELINE_CONCERNS: Dict[str, str] = {
    "stack": "already included in every route through CORE_DOCS.",
    "failure": "already included in every route through CORE_DOCS.",
    "interaction": "already included in every route through CORE_DOCS.",
}
