"""Keyword-to-concern inference rules for workflow routing."""

from __future__ import annotations

from typing import Tuple


REQUEST_CONCERN_HINTS: Tuple[Tuple[str, Tuple[str, ...]], ...] = (
    (
        "swift",
        (
            r"\bswift\b",
            r"\bswiftui\b",
            r"\bswift package\b",
            r"\bswift packages\b",
            "\uc2a4\uc704\ud504\ud2b8",
            "\uc2a4\uc704\ud504\ud2b8ui",
        ),
    ),
    (
        "design-system",
        (
            r"\bdesign system\b",
            r"\bdesign-system\b",
            r"\bdesign tokens?\b",
            r"\btokens?\b",
            r"\bthemes?\b",
            r"\bprimitives?\b",
            "\ub514\uc790\uc778 \uc2dc\uc2a4\ud15c",
            "\ub514\uc790\uc778\uc2dc\uc2a4\ud15c",
            "\ud1a0\ud070",
            "\ud14c\ub9c8",
            "\ud504\ub9ac\ubbf8\ud2f0\ube0c",
        ),
    ),
    (
        "architecture",
        (
            r"\barchitecture\b",
            r"\barchitectural\b",
            r"\bboundar(?:y|ies)\b",
            r"\blayers?\b",
            "\uc544\ud0a4\ud14d\ucc98",
            "\uacbd\uacc4",
            "\ub808\uc774\uc5b4",
        ),
    ),
    (
        "structure",
        (
            r"\bstructure\b",
            r"\bcode structure\b",
            r"\bmodule structure\b",
            r"\bfile structure\b",
            r"\bpackage structure\b",
            "\uad6c\uc870\ud654",
            "\ucf54\ub4dc \uad6c\uc870",
            "\ubaa8\ub4c8 \uad6c\uc870",
            "\ud328\ud0a4\uc9c0 \uad6c\uc870",
        ),
    ),
    (
        "testing",
        (
            r"\btests?\b",
            r"\btesting\b",
            r"\bunit test\b",
            r"\bintegration test\b",
            r"\bregression\b",
            r"\bverification\b",
            "\ud14c\uc2a4\ud2b8",
            "\uac80\uc99d",
        ),
    ),
    (
        "seo",
        (
            r"\bseo\b",
            r"\bsearch engine optimization\b",
            r"\bai search\b",
            r"\bai search optimization\b",
            r"\bgenerative ai search\b",
            r"\bgenerative ai\b",
            r"\bai overviews?\b",
            r"\bai mode\b",
            r"\baeo\b",
            r"\bgeo\b",
            r"\banswer engine(?: optimization)?\b",
            r"\bllms(?:\.txt|-txt)?\b",
            r"\bsitemap\b",
            r"\brobots(?:\.txt)?\b",
            r"\bcanonical\b",
            r"\bopen graph\b",
            r"\bopengraph\b",
            r"\bog image\b",
            r"\bstructured data\b",
            "\uac80\uc0c9 \ucd5c\uc801\ud654",
            "ai \uac80\uc0c9",
            "\uc0dd\uc131\ud615 ai",
            "\uc0dd\uc131\ud615 \uac80\uc0c9",
            "\uc0ac\uc774\ud2b8\ub9f5",
            "\ub85c\ubd07.txt",
            "\uce90\ub178\ub2c8\uceec",
            "\uc624\ud508 \uadf8\ub798\ud504",
            "\uad6c\uc870\ud654 \ub370\uc774\ud130",
        ),
    ),
    (
        "runtime-url",
        (
            r"\bruntime url\b",
            r"\bruntime urls\b",
            r"\bbase url\b",
            r"\bapi url\b",
            r"\bapi origin\b",
            r"\bcallback url\b",
            r"\bredirect_uri\b",
            r"\bredirect uri\b",
            r"\bwebhook endpoint\b",
            r"\bcors origin\b",
            r"\basset host\b",
            r"\bcdn origin\b",
            r"\benvironment-specific url\b",
            r"\benvironment specific url\b",
            "\ud658\uacbd\ubcc4 url",
            "\ud658\uacbd\ubcc4 \ub7f0\ud0c0\uc784 url",
            "\ub7f0\ud0c0\uc784 url",
            "\ucf5c\ubc31 url",
            "\ub9ac\ub2e4\uc774\ub809\ud2b8 uri",
            "\uc6f9\ud6c5",
        ),
    ),
)
