"""Keyword-to-concern inference rules for workflow routing."""

from __future__ import annotations

from typing import Tuple


REQUEST_CONCERN_HINTS: Tuple[Tuple[str, Tuple[str, ...]], ...] = (
    (
        "swift",
        (
            r"\bswift\b",
            r"\bswiftui\b",
            r"\bswift package\b",
            r"\bswift packages\b",
            "\uc2a4\uc704\ud504\ud2b8",
            "\uc2a4\uc704\ud504\ud2b8ui",
        ),
    ),
    (
        "design-system",
        (
            r"\bdesign system\b",
            r"\bdesign-system\b",
            r"\bdesign tokens?\b",
            r"\btokens?\b",
            r"\bthemes?\b",
            r"\bprimitives?\b",
            "\ub514\uc790\uc778 \uc2dc\uc2a4\ud15c",
            "\ub514\uc790\uc778\uc2dc\uc2a4\ud15c",
            "\ud1a0\ud070",
            "\ud14c\ub9c8",
            "\ud504\ub9ac\ubbf8\ud2f0\ube0c",
        ),
    ),
    (
        "accessibility",
        (
            r"\baccessib(?:le|ility)\b",
            r"\ba11y\b",
            r"\bi18n\b",
            r"\blocali[sz]ation\b",
            r"\blocale\b",
            r"\bnumbers?\b",
            r"\bnumeric\b",
            r"\bnumber format(?:ting)?\b",
            r"\bformatted values?\b",
            r"\bdisplay values?\b",
            r"\bunits?\b",
            r"\bunit labels?\b",
            r"\bmeasurements?\b",
            r"\bcurrenc(?:y|ies)\b",
            r"\bpercent(?:age|ages)?\b",
            r"\brates?\b",
            r"\bstorage sizes?\b",
            r"\bdurations?\b",
            "\uc811\uadfc\uc131",
            "\ub85c\ucf00\uc77c",
            "\ub85c\uceec\ub77c\uc774\uc81c\uc774\uc158",
            "\ud604\uc9c0\ud654",
            "\uc22b\uc790",
            "\uc22b\uc790 \ud45c\uae30",
            "\ub2e8\uc704",
            "\uce21\uc815\uac12",
            "\ud45c\uc2dc\uac12",
            "\ud45c\uc2dc \uac12",
            "\ud45c\uae30",
            "\ud654\ud3d0",
            "\ud37c\uc13c\ud2b8",
            "\ube44\uc728",
        ),
    ),
    (
        "architecture",
        (
            r"\barchitecture\b",
            r"\barchitectural\b",
            r"\bboundar(?:y|ies)\b",
            r"\blayers?\b",
            "\uc544\ud0a4\ud14d\ucc98",
            "\uacbd\uacc4",
            "\ub808\uc774\uc5b4",
        ),
    ),
    (
        "structure",
        (
            r"\bstructure\b",
            r"\bcode structure\b",
            r"\bmodule structure\b",
            r"\bfile structure\b",
            r"\bpackage structure\b",
            "\uad6c\uc870\ud654",
            "\ucf54\ub4dc \uad6c\uc870",
            "\ubaa8\ub4c8 \uad6c\uc870",
            "\ud328\ud0a4\uc9c0 \uad6c\uc870",
        ),
    ),
    (
        "testing",
        (
            r"\btests?\b",
            r"\btesting\b",
            r"\bunit test\b",
            r"\bintegration test\b",
            r"\bregression\b",
            r"\bverification\b",
            r"\bdefinition of done\b",
            r"\bdone checklist\b",
            r"\bcompletion checklist\b",
            "\ud14c\uc2a4\ud2b8",
            "\uac80\uc99d",
            "\uc644\ub8cc \uae30\uc900",
        ),
    ),
    (
        "compose",
        (
            r"\bjetpack compose\b",
            r"\bcompose ui\b",
            r"\bcomposable\b",
            r"\blazycolumn\b",
            r"\blazyrow\b",
            r"\bderivedstateof\b",
            r"\bcollectasstatewithlifecycle\b",
            r"\bmodifier\.node\b",
            r"\b@immutable\b",
            r"\b@stable\b",
            "\ucef4\ud3ec\uc988",
        ),
    ),
    (
        "performance",
        (
            r"\bperformance\b",
            r"\bperf\b",
            r"\bjank\b",
            r"\brecomposition\b",
            r"\brecompose\b",
            r"\bskippab(?:le|ility)\b",
            r"\bstability report\b",
            r"\bcompiler reports?\b",
            r"\bmacrobenchmark\b",
            r"\bbaseline profiles?\b",
            r"\br8\b",
            r"\bperfetto\b",
            "\uc131\ub2a5",
            "\uc7b0\ud06c",
            "\ub9ac\ucef4\ud3ec\uc9c0\uc158",
        ),
    ),
    (
        "skill-card",
        (
            r"\bskill cards?\b",
            r"\bskill docs?\b",
            r"\bskill anatomy\b",
            r"\bcard anatomy\b",
            r"\bagent skills?\b",
            "\uc2a4\ud0ac\ubb38\uc11c",
            "\uc2a4\ud0ac \ubb38\uc11c",
            "\uc2a4\ud0ac \uce74\ub4dc",
        ),
    ),
    (
        "writing",
        (
            r"\barticle\b",
            r"\bblog post\b",
            r"\bessay\b",
            r"\brelease notes?\b",
            r"\bcopywriting\b",
            r"\bmarketing copy\b",
            r"\bweb copy\b",
            r"\bmicrocopy\b",
            r"\bvoice\b",
            r"\btone\b",
            r"\bhumanize\b",
            r"\bhuman[- ]authored\b",
            r"\bai[- ]writing\b",
            r"\bless ai[- ]sounding\b",
            r"\bwrite(?: an?| the)?\s+(article|blog|essay|post|release note|intro|introduction)\b",
            "\uae00\uc744 \uc368",
            "\uae00 \uc368",
            "\uae00\uc4f0\uae30",
            "\uc18c\uac1c\ud558\ub294 \uae00",
            "\uc18c\uac1c\uae00",
            "\uc544\ud2f0\ud074",
            "\ube14\ub85c\uadf8",
            "\uc5d0\uc138\uc774",
            "\ub9b4\ub9ac\uc988 \ub178\ud2b8",
            "\uc720\uc800 \uce74\ud53c",
            "\ub9c8\ucf00\ud305 \uce74\ud53c",
            "\ubb38\uccb4",
            "\ub9d0\ud22c",
            "\uc5b4\ud22c",
            "\uc2a4\ud0c0\uc77c",
            "\ub0b4 \uc2a4\ud0c0\uc77c",
            "\uc874\ub300",
            r"\uc791\uc131\s*\ub2e4\uc2dc",
            r"\ub2e4\uc2dc\s*(\uc791\uc131|\uc4f0|\uc815\ub9ac)",
            "\ud1a4\uc564\ub9e4\ub108",
            "\uc790\uc5f0\uc2a4\ub7fd\uac8c",
            "ai \ud2f0",
            "\uc0ac\ub78c\uc774 \uc4f4 \uac83\ucc98\ub7fc",
        ),
    ),
    (
        "source-driven",
        (
            r"\bsource[- ]driven\b",
            r"\bofficial docs?\b",
            r"\bversioned docs?\b",
            r"\bsdk docs?\b",
            r"\bframework docs?\b",
            "\uacf5\uc2dd \ubb38\uc11c",
            "\ubc84\uc804 \ubb38\uc11c",
        ),
    ),
    (
        "doubt-driven",
        (
            r"\bdoubt[- ]driven\b",
            r"\badversarial review\b",
            r"\bchallenge assumptions?\b",
            r"\bclaim.*doubt\b",
            "\ud68c\uc758",
            "\ubc18\ub300 \uac80\ud1a0",
            "\uac00\uc815 \uac80\ud1a0",
        ),
    ),
    (
        "incremental",
        (
            r"\bincremental\b",
            r"\bvertical slices?\b",
            r"\bthin slices?\b",
            r"\bcontract-first\b",
            r"\brisk-first\b",
            "\uc21c\ucc28",
            "\uc2ac\ub77c\uc774\uc2a4",
            "\uc810\uc9c4\uc801",
        ),
    ),
    (
        "deprecation",
        (
            r"\bdeprecat(?:e|ed|ion)\b",
            r"\bsunset\b",
            r"\bremove old\b",
            "\ub514\ud504\ub9ac\ucf00\uc774\uc158",
            "\uc81c\uac70",
        ),
    ),
    (
        "migration",
        (
            r"\bmigration\b",
            r"\bmigrate\b",
            r"\bcompatibility\b",
            "\ub9c8\uc774\uadf8\ub808\uc774\uc158",
            "\ud638\ud658\uc131",
        ),
    ),
    (
        "ci",
        (
            r"\bci\b",
            r"\bci/cd\b",
            r"\bgithub actions?\b",
            r"\bworkflow files?\b",
            r"\bpipeline\b",
            r"\bautomation\b",
            "\ud30c\uc774\ud504\ub77c\uc778",
            "\uc790\ub3d9\ud654",
        ),
    ),
    (
        "webperf",
        (
            r"\bwebperf\b",
            r"\bweb performance\b",
            r"\bcore web vitals\b",
            r"\blighthouse\b",
            r"\bbundle size\b",
            r"\blayout shift\b",
            "\uc6f9 \uc131\ub2a5",
            "\ub77c\uc774\ud2b8\ud558\uc6b0\uc2a4",
        ),
    ),
    (
        "browser-testing",
        (
            r"\bbrowser testing\b",
            r"\bdevtools\b",
            r"\bconsole errors?\b",
            r"\bnetwork waterfall\b",
            r"\bdom\b",
            "\ube0c\ub77c\uc6b0\uc800 \ud14c\uc2a4\ud2b8",
            "\ub370\ube0c\ud234",
        ),
    ),
    (
        "metering",
        (
            r"\bspill\b",
            r"\bmetering\b",
            r"\busage telemetry\b",
            r"\busage metering\b",
            r"\btoken metering\b",
            r"\bworkflow label bridge\b",
            r"\blabel bridge\b",
            r"\bruntime label handoff\b",
            "\uc0ac\uc6a9\ub7c9",
            "\ubbf8\ud130\ub9c1",
            "\ud1a0\ud070 \ubbf8\ud130\ub9c1",
            "\uc2a4\ud544",
        ),
    ),
    (
        "credential-broker",
        (
            r"\bcredential brokers?\b",
            r"\bcredential proxies?\b",
            r"\bcredential vaults?\b",
            r"\bbrokered credentials?\b",
            r"\bagent credentials?\b",
            r"\bagent credential boundary\b",
            r"\bcapability tokens?\b",
            r"\begress control\b",
            r"\begress filtering\b",
            r"\bhuman[- ]in[- ]the[- ]loop approval\b",
            r"\bapproval loops?\b.*\bcredentials?\b",
            "\uc790\uaca9 \uc99d\uba85 \ube0c\ub85c\ucee4",
            "\uc790\uaca9\uc99d\uba85 \ube0c\ub85c\ucee4",
            "\ud06c\ub9ac\ub374\uc15c \ube0c\ub85c\ucee4",
            "\uc5d0\uc774\uc804\ud2b8 \uc790\uaca9 \uc99d\uba85",
            "\uc5d0\uc774\uc804\ud2b8 \ud06c\ub9ac\ub374\uc15c",
            "\uad8c\ud55c \ube0c\ub85c\ucee4",
            "\uc2b9\uc778 \ub8e8\ud504",
            "\uc774\uadf8\ub808\uc2a4",
        ),
    ),
    (
        "seo",
        (
            r"\bseo\b",
            r"\bsearch engine optimization\b",
            r"\bai search\b",
            r"\bai search optimization\b",
            r"\bgenerative ai search\b",
            r"\bgenerative ai\b",
            r"\bai overviews?\b",
            r"\bai mode\b",
            r"\baeo\b",
            r"\bgeo\b",
            r"\banswer engine(?: optimization)?\b",
            r"\bllms(?:\.txt|-txt)?\b",
            r"\bsitemap\b",
            r"\brobots(?:\.txt)?\b",
            r"\bcanonical\b",
            r"\bopen graph\b",
            r"\bopengraph\b",
            r"\bog image\b",
            r"\bstructured data\b",
            "\uac80\uc0c9 \ucd5c\uc801\ud654",
            "ai \uac80\uc0c9",
            "\uc0dd\uc131\ud615 ai",
            "\uc0dd\uc131\ud615 \uac80\uc0c9",
            "\uc0ac\uc774\ud2b8\ub9f5",
            "\ub85c\ubd07.txt",
            "\uce90\ub178\ub2c8\uceec",
            "\uc624\ud508 \uadf8\ub798\ud504",
            "\uad6c\uc870\ud654 \ub370\uc774\ud130",
        ),
    ),
    (
        "runtime-url",
        (
            r"\bruntime url\b",
            r"\bruntime urls\b",
            r"\bbase url\b",
            r"\bapi url\b",
            r"\bapi origin\b",
            r"\bcallback url\b",
            r"\bredirect_uri\b",
            r"\bredirect uri\b",
            r"\bwebhook endpoint\b",
            r"\bcors origin\b",
            r"\basset host\b",
            r"\bcdn origin\b",
            r"\benvironment-specific url\b",
            r"\benvironment specific url\b",
            "\ud658\uacbd\ubcc4 url",
            "\ud658\uacbd\ubcc4 \ub7f0\ud0c0\uc784 url",
            "\ub7f0\ud0c0\uc784 url",
            "\ucf5c\ubc31 url",
            "\ub9ac\ub2e4\uc774\ub809\ud2b8 uri",
            "\uc6f9\ud6c5",
        ),
    ),
)
